namespace TM.Web.Application.Dtos.Design;

public record ChapterPlanDto(
    string Id,
    string Name,
    string Category,
    string? CategoryId,
    bool IsEnabled,
    string? SourceBookId,
    Dictionary<string, int> DependencyModuleVersions,
    string ChapterTitle,
    int ChapterNumber,
    string Volume,
    string EstimatedWordCount,
    string ChapterTheme,
    string ReaderExperienceGoal,
    string MainGoal,
    string MacroPhase,
    string TacticalArcId,
    string TacticalArcTitle,
    string ChapterType,
    string ConflictScore,
    string CoreEvent,
    List<string> AllowedEntities,
    string ResistanceSource,
    string KeyTurn,
    string Hook,
    string StatusMarkers,
    string TemporalAnchor,
    string SpatialAnchor,
    string TimelineCoordinate,
    bool IsSingularityEvent,
    string BufferRole,
    string ForeshadowingTier,
    string ForeshadowingRole,
    string WorldInfoDrop,
    string CharacterArcProgress,
    string MainPlotProgress,
    string Foreshadowing,
    List<string> ReferencedCharacterNames,
    List<string> ReferencedFactionNames,
    List<string> ReferencedLocationNames,
    DateTime CreatedAt,
    DateTime UpdatedAt) : IBusinessDataDto;

public record ChapterPlanUpsertDto(
    string Name,
    string Category = "",
    string? CategoryId = null,
    bool IsEnabled = true,
    string? SourceBookId = null,
    string? ProjectId = null,
    Dictionary<string, int>? DependencyModuleVersions = null,
    string ChapterTitle = "",
    int ChapterNumber = 0,
    string Volume = "",
    string EstimatedWordCount = "",
    string ChapterTheme = "",
    string ReaderExperienceGoal = "",
    string MainGoal = "",
    string MacroPhase = "",
    string TacticalArcId = "",
    string TacticalArcTitle = "",
    string ChapterType = "",
    string ConflictScore = "",
    string CoreEvent = "",
    List<string>? AllowedEntities = null,
    string ResistanceSource = "",
    string KeyTurn = "",
    string Hook = "",
    string StatusMarkers = "",
    string TemporalAnchor = "",
    string SpatialAnchor = "",
    string TimelineCoordinate = "",
    bool IsSingularityEvent = false,
    string BufferRole = "",
    string ForeshadowingTier = "",
    string ForeshadowingRole = "",
    string WorldInfoDrop = "",
    string CharacterArcProgress = "",
    string MainPlotProgress = "",
    string Foreshadowing = "",
    List<string>? ReferencedCharacterNames = null,
    List<string>? ReferencedFactionNames = null,
    List<string>? ReferencedLocationNames = null);

public record ChapterPlanSummaryRewriteResultDto(
    int MatchedCount,
    int UpdatedCount,
    IReadOnlyList<ChapterPlanDto> Items);
