namespace TM.Web.Application.Dtos.Design;

public record CharacterRuleDto(
    string Id,
    string Name,
    string Category,
    string? CategoryId,
    bool IsEnabled,
    string? SourceBookId,
    string CharacterType,
    string Gender,
    string Age,
    string Identity,
    string Race,
    string Appearance,
    string Want,
    string Need,
    string FlawBelief,
    string GrowthPath,
    string TargetCharacterName,
    string RelationshipType,
    string EmotionDynamic,
    string CombatSkills,
    string NonCombatSkills,
    string SpecialAbilities,
    string SignatureItems,
    string CommonItems,
    string PersonalAssets,
    DateTime CreatedAt,
    DateTime UpdatedAt) : IBusinessDataDto;

public record CharacterRuleUpsertDto(
    string Name,
    string Category = "",
    string? CategoryId = null,
    bool IsEnabled = true,
    string? SourceBookId = null,
    string? ProjectId = null,
    string CharacterType = "",
    string Gender = "",
    string Age = "",
    string Identity = "",
    string Race = "",
    string Appearance = "",
    string Want = "",
    string Need = "",
    string FlawBelief = "",
    string GrowthPath = "",
    string TargetCharacterName = "",
    string RelationshipType = "",
    string EmotionDynamic = "",
    string CombatSkills = "",
    string NonCombatSkills = "",
    string SpecialAbilities = "",
    string SignatureItems = "",
    string CommonItems = "",
    string PersonalAssets = "");
