namespace TM.Web.Application.Dtos.Design;

public record CreativeMaterialDto(
    string Id,
    string Name,
    string Category,
    string? CategoryId,
    bool IsEnabled,
    string? SourceBookId,
    string Icon,
    string? SourceBookName,
    string Genre,
    string OverallIdea,
    string WorldBuildingMethod,
    string PowerSystemDesign,
    string EnvironmentDescription,
    string FactionDesign,
    string WorldviewHighlights,
    string ProtagonistDesign,
    string SupportingRoles,
    string CharacterRelations,
    string GoldenFingerDesign,
    string CharacterHighlights,
    string PlotStructure,
    string ConflictDesign,
    string ClimaxArrangement,
    string ForeshadowingTechnique,
    string PlotHighlights,
    DateTime CreatedAt,
    DateTime UpdatedAt) : IBusinessDataDto;

public record CreativeMaterialUpsertDto(
    string Name,
    string Category = "",
    string? CategoryId = null,
    bool IsEnabled = true,
    string? SourceBookId = null,
    string? ProjectId = null,
    string Icon = "💡",
    string? SourceBookName = null,
    string Genre = "",
    string OverallIdea = "",
    string WorldBuildingMethod = "",
    string PowerSystemDesign = "",
    string EnvironmentDescription = "",
    string FactionDesign = "",
    string WorldviewHighlights = "",
    string ProtagonistDesign = "",
    string SupportingRoles = "",
    string CharacterRelations = "",
    string GoldenFingerDesign = "",
    string CharacterHighlights = "",
    string PlotStructure = "",
    string ConflictDesign = "",
    string ClimaxArrangement = "",
    string ForeshadowingTechnique = "",
    string PlotHighlights = "");
