namespace TM.Web.Application.Dtos.Design;

public record BookAnalysisDto(
    string Id,
    string Name,
    string Category,
    string? CategoryId,
    bool IsEnabled,
    string? SourceBookId,
    string Icon,
    string Author,
    string Genre,
    string SourceUrl,
    string SourceBookTitle,
    string SourceAuthor,
    string SourceGenre,
    string SourceKeywords,
    string SourceSite,
    int ChapterCount,
    int TotalWordCount,
    DateTime? CrawledAt,
    string WorldBuildingMethod,
    string PowerSystemDesign,
    string EnvironmentDescription,
    string FactionDesign,
    string WorldviewHighlights,
    string ProtagonistDesign,
    string SupportingRoles,
    string CharacterRelations,
    string GoldenFingerDesign,
    string CharacterHighlights,
    string PlotStructure,
    string ConflictDesign,
    string ClimaxArrangement,
    string ForeshadowingTechnique,
    string PlotHighlights,
    DateTime CreatedAt,
    DateTime UpdatedAt) : IBusinessDataDto;

public record BookAnalysisUpsertDto(
    string Name,
    string Category = "",
    string? CategoryId = null,
    bool IsEnabled = true,
    string? SourceBookId = null,
    string Icon = "📖",
    string Author = "",
    string Genre = "",
    string SourceUrl = "",
    string SourceBookTitle = "",
    string SourceAuthor = "",
    string SourceGenre = "",
    string SourceKeywords = "",
    string SourceSite = "",
    int ChapterCount = 0,
    int TotalWordCount = 0,
    DateTime? CrawledAt = null,
    string WorldBuildingMethod = "",
    string PowerSystemDesign = "",
    string EnvironmentDescription = "",
    string FactionDesign = "",
    string WorldviewHighlights = "",
    string ProtagonistDesign = "",
    string SupportingRoles = "",
    string CharacterRelations = "",
    string GoldenFingerDesign = "",
    string CharacterHighlights = "",
    string PlotStructure = "",
    string ConflictDesign = "",
    string ClimaxArrangement = "",
    string ForeshadowingTechnique = "",
    string PlotHighlights = "");
