namespace TM.Web.Application.Dtos.Design;

public record ChapterBlueprintDto(
    string Id,
    string Name,
    string Category,
    string? CategoryId,
    bool IsEnabled,
    string? SourceBookId,
    Dictionary<string, int> DependencyModuleVersions,
    string ChapterId,
    string OneLineStructure,
    string PacingCurve,
    int SceneNumber,
    string SceneTitle,
    string PovCharacter,
    string EstimatedWordCount,
    string Opening,
    string Development,
    string Turning,
    string Ending,
    string InfoDrop,
    string Cast,
    string Locations,
    string Factions,
    string ItemsClues,
    DateTime CreatedAt,
    DateTime UpdatedAt) : IBusinessDataDto;

public record ChapterBlueprintUpsertDto(
    string Name,
    string Category = "",
    string? CategoryId = null,
    bool IsEnabled = true,
    string? SourceBookId = null,
    Dictionary<string, int>? DependencyModuleVersions = null,
    string ChapterId = "",
    string OneLineStructure = "",
    string PacingCurve = "",
    int SceneNumber = 0,
    string SceneTitle = "",
    string PovCharacter = "",
    string EstimatedWordCount = "",
    string Opening = "",
    string Development = "",
    string Turning = "",
    string Ending = "",
    string InfoDrop = "",
    string Cast = "",
    string Locations = "",
    string Factions = "",
    string ItemsClues = "");
