namespace TM.Web.Application.Dtos.Design;

public record PlotRuleDto(
    string Id,
    string Name,
    string Category,
    string? CategoryId,
    bool IsEnabled,
    string? SourceBookId,
    string TargetVolume,
    string AssignedVolume,
    string OneLineSummary,
    string EventType,
    string StoryPhase,
    string PrerequisitesTrigger,
    string MainCharacters,
    string KeyNpcs,
    string Location,
    string TimeDuration,
    string StepTitle,
    string Goal,
    string Conflict,
    string Result,
    string EmotionCurve,
    string MainPlotPush,
    string CharacterGrowth,
    string WorldReveal,
    string RewardsClues,
    DateTime CreatedAt,
    DateTime UpdatedAt) : IBusinessDataDto;

public record PlotRuleUpsertDto(
    string Name,
    string Category = "",
    string? CategoryId = null,
    bool IsEnabled = true,
    string? SourceBookId = null,
    string TargetVolume = "",
    string AssignedVolume = "",
    string OneLineSummary = "",
    string EventType = "",
    string StoryPhase = "",
    string PrerequisitesTrigger = "",
    string MainCharacters = "",
    string KeyNpcs = "",
    string Location = "",
    string TimeDuration = "",
    string StepTitle = "",
    string Goal = "",
    string Conflict = "",
    string Result = "",
    string EmotionCurve = "",
    string MainPlotPush = "",
    string CharacterGrowth = "",
    string WorldReveal = "",
    string RewardsClues = "");
