namespace TM.Web.Application.Dtos.Design;

public record VolumeDesignDto(
    string Id,
    string Name,
    string Category,
    string? CategoryId,
    bool IsEnabled,
    string? SourceBookId,
    Dictionary<string, int> DependencyModuleVersions,
    int VolumeNumber,
    string VolumeTitle,
    string VolumeTheme,
    string StageGoal,
    string EstimatedWordCount,
    int TargetChapterCount,
    int StartChapter,
    int EndChapter,
    string MainConflict,
    string PressureSource,
    string KeyEvents,
    string OpeningState,
    string EndingState,
    string ChapterAllocationOverview,
    string PlotAllocation,
    string ChapterGenerationHints,
    List<string> ReferencedCharacterNames,
    List<string> ReferencedFactionNames,
    List<string> ReferencedLocationNames,
    DateTime CreatedAt,
    DateTime UpdatedAt) : IBusinessDataDto;

public record VolumeDesignUpsertDto(
    string Name,
    string Category = "",
    string? CategoryId = null,
    bool IsEnabled = true,
    string? SourceBookId = null,
    Dictionary<string, int>? DependencyModuleVersions = null,
    int VolumeNumber = 0,
    string VolumeTitle = "",
    string VolumeTheme = "",
    string StageGoal = "",
    string EstimatedWordCount = "",
    int TargetChapterCount = 0,
    int StartChapter = 0,
    int EndChapter = 0,
    string MainConflict = "",
    string PressureSource = "",
    string KeyEvents = "",
    string OpeningState = "",
    string EndingState = "",
    string ChapterAllocationOverview = "",
    string PlotAllocation = "",
    string ChapterGenerationHints = "",
    List<string>? ReferencedCharacterNames = null,
    List<string>? ReferencedFactionNames = null,
    List<string>? ReferencedLocationNames = null);
